"""add submission idempotency constraint

Revision ID: 26f52d162d9c
Revises: 0853df469b35
Create Date: 2026-09-24 18:17:00.447283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f52d162d9c'
down_revision: Union[str, Sequence[str], None] = '0853df469b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_submission_widget_idempotency', 'submissions', ['widget_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_submission_widget_idempotency', 'submissions', type_='unique')
    # ### end Alembic commands ###
